/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-1',
  aws_appsync_graphqlEndpoint:
    'https://stp45kmz7rgjjgdoag245wlkxq.appsync-api.us-west-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-west-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-ekn65cf5uzehnpto6y3svd3edu',
  aws_cognito_identity_pool_id:
    'us-west-1:9edb2243-9814-49a9-b343-f8030c2e74d0',
  aws_cognito_region: 'us-west-1',
  aws_user_pools_id: 'us-west-1_L4OtDLDGE',
  aws_user_pools_web_client_id: '52leri14mtil9k6j089soqk4fq',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      'REQUIRES_LOWERCASE',
      'REQUIRES_NUMBERS',
      'REQUIRES_SYMBOLS',
      'REQUIRES_UPPERCASE',
    ],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
};

export default awsmobile;
