/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-west-1',
    aws_cognito_identity_pool_id:
        'us-west-1:5995aad3-e7e5-4558-9960-61ce9d13b017',
    aws_cognito_region: 'us-west-1',
    aws_user_pools_id: 'us-west-1_JEnMb5Dnl',
    aws_user_pools_web_client_id: '432c28u0qp2d1fmh3eksc95kek',
    oauth: {},
    aws_cognito_username_attributes: ['EMAIL'],
    aws_cognito_social_providers: [],
    aws_cognito_signup_attributes: ['EMAIL'],
    aws_cognito_mfa_configuration: 'OFF',
    aws_cognito_mfa_types: ['SMS'],
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: [],
    },
    aws_cognito_verification_mechanisms: ['EMAIL'],
    aws_appsync_graphqlEndpoint:
        'https://jffd64u7zzcs5kfmhaiuvezyfi.appsync-api.us-west-1.amazonaws.com/graphql',
    aws_appsync_region: 'us-west-1',
    aws_appsync_authenticationType: 'API_KEY',
    aws_appsync_apiKey: 'da2-37ytscbmdbfpbhp2sfbanwma54',
}

export default awsmobile
